data:
  root_dir: '/mounts/datasets/datasets/2025-ZooCamChallenge'
  batch_size: 32
  num_workers: 8
  valid_ratio: 0.2
  img_size: 224
  resize_size: 256

nepochs: 40
warmup_epochs: 5

logging:
  logdir: "./logs"

model:
  class: HfModel
  name: microsoft/resnet-50
  freeze_backbone: False

loss:
  class: FocalLoss
  gamma: 1.0

optim:
  algo: AdamW
  head_lr: 1e-3
  backbone_lr: 1e-5
  finetune_head_lr: 1e-4
  scheduler: CosineAnnealing