data:
  root_dir: '/mounts/datasets/datasets/2025-ZooCamChallenge'
  batch_size: 64       # Réduit un peu car ResNet est plus gros que Linear
  num_workers: 4
  valid_ratio: 0.2

nepochs: 20            # 20 époques suffisent souvent pour du finetuning

logging:
  logdir: "./logs"

model:
  class: HfModel                 # Nom de la classe Python à appeler
  name: microsoft/resnet-50      # Nom du modèle sur Hugging Face
  freeze_backbone: False         # Optionnel: True si tu veux geler les poids initiaux

loss:
  class: FocalLoss               # Nom de ta nouvelle classe de loss
  alpha: 1
  gamma: 2

optim:
  algo: Adam                     # On pourra le lire dans main.py
  lr: 0.0001                     # Learning rate plus bas pour le finetuning